### ISSUE TITLE
The messages are too large

### ISSUE THREAD

**Issue by rwols** [rchl/lsp-log-parser#2]
The individual messages take up a lot of space. Consequently it's hard to debug a lot of messages. Can the messages be made smaller?

**Comment by rchl** [comment]
At one point I didn't show the payload in the main view so then messages took half the height.

I think showing payloads is not that useful as such a short preview doesn't really tell you much about it, but it allows you to differentiate at a glance if the response is empty and should you even bother clicking it to see expanded view. So I don't think they are entirely useless.

Could also try just with smaller text size.

**Comment by rwols** [comment]
Perhaps it’s possible to position the request and the response on the same line? There should be enough horizontal space for that :)

**Comment by rchl** [comment]
Then you wouldn't see the original flow of messages which can be important for debugging.

**Comment by rwols** [comment]
You're right, it would lose information if presented that way.

**Comment by rchl** [comment]
Remove payload preview and changed to expand payload within the message on click.
